### ISSUE TITLE
Severe weather probabilities for the Caribbean.

### ISSUE THREAD

**Issue by tejedawx** [brianhempel/nadocast#2]
Hey. I was wondering how hard would be create maps with severe weather probabilities for Puerto Rico and Dominican Republic. We have a lot of severe weather event that people don't even report. We have the HREFv3 nest and the SREF reach here. I'd pay to get that data.

**Comment by brianhempel** [comment]
I'd first check that the GRIB2 files on data.nadocast.com don't already cover it, e.g. http://data.nadocast.com/202305/20230516/t18z/nadocast_2022_models_conus_hail_20230516_t18z_f02-17.grib2 You may need https://www.ncdc.noaa.gov/wct/ to check (I don't have Java on my computer right now).

But yes, it would be non-trivial and would require several assumptions about climatology.

**Comment by tejedawx** [comment]
Good Afternoon Brian. I just opened one of the GRIB2 files in Unidata Integrated Data Viewer (IDV) and it seems like the extend of the data doesn’t reach the Caribbean. I think is because the HREFv3 data you are using is from the CONUS Domain, Puerto Rico has it own domain. I’d be glad if I can see the data from the Puerto Rico HREF Domain. I can even pay for it since I need it for their weather app I wanna Build. I Attached a screenshot of the data display. Thanks.￼

**Comment by tejedawx** [comment]
Hello, you can see the attachment in the mail but it seems like you can't  here. Apologies for that, didn't notice until now. Id be glad if I get a positive answer since we need that information. Hope you have a great day. 

Thanks.
