### ISSUE TITLE
Outage - No data since 8/3/2023

### ISSUE THREAD

**Issue by WXFanatics** [brianhempel/nadocast#3]
I'm not fully sure how to get a hold of you, and the only way I might be able to get your attention is to write an issue about it here.

There hasn't been any data since August 3rd. Is this an unexpected outage or is there work going on behind the scenes? http://data.nadocast.com/202308/

Thanks!
Michael

**Comment by brianhempel** [comment]
Sorry, I noticed it went down but I was leaving town. It can’t be fixed remotely so it will be down for three weeks at least.

**Comment by WXFanatics** [comment]
Thank you for the reply and the update.

**Comment by WXFanatics** [comment]
Seems to be back now! Thank you.
